### ISSUE TITLE
RSI bug

### ISSUE THREAD

**Issue by thunderwin** [oransel/node-talib#106]
# Fatal error in , line 0
# Check failed: receiver.IsJSFunction().
#
#
#
#FailureMessage Object: 0x7ffeefbf5330
 1: 0x100124bf2 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/usr/local/bin/node]
 2: 0x10104fca3 V8_Fatal(char const*, ...) [/usr/local/bin/node]
 3: 0x1005901d1 v8::internal::JSReceiver::GetCreationContext() [/usr/local/bin/node]
 4: 0x10021c998 v8::Object::CreationContext() [/usr/local/bin/node]
 5: 0x1000026e0 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 6: 0x108008115 Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*, Nan::AsyncResource*) const [/Users/nathan/coinTradeTools/feature/node_modules/talib/build/Release/talib.node]
 7: 0x10800800c Nan::Callback::Call(int, v8::Local<v8::Value>*) const [/Users/nathan/coinTradeTools/feature/node_modules/talib/build/Release/talib.node]
 8: 0x10800707e REPORT_INTERNAL_ERROR(Nan::Callback*, char const*) [/Users/nathan/coinTradeTools/feature/node_modules/talib/build/Release/talib.node]
 9: 0x1080064c7 Execute(Nan::FunctionCallbackInfo<v8::Value> const&) [/Users/nathan/coinTradeTools/feature/node_modules/talib/build/Release/talib.node]
10: 0x108008ccd Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/nathan/coinTradeTools/feature/node_modules/talib/build/Release/talib.node]
11: 0x100272038 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
12: 0x1002715cc v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]

**Comment by lwedel** [comment]
I had similar cases - it may be due to the wrong parameters provided when You are running the method. 
Do you mind sharing the code, You are getting this error with.
