### ISSUE TITLE
Does not run on AWS ec2 t3 and t4g instances

### ISSUE THREAD

**Issue by Milan4e** [oransel/node-talib#109]
Hi,

First of all thank you for this amazing library. Probably the most robust TA package out there.

I am having issues running this on AWS ec2 instance and I am getting different errors on different instances.

T3 instance, node 14.17.6

```
{\"name\":\"Error\",\"message\":\"/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/app/current/node_modules/talib/build/Release/talib.node)\",\"stack\":\"Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/app/current/node_modules/talib/build/Release/talib.node)\\n
```

T4G instance, node 14.17.6

```
{\"name\":\"Error\",\"message\":\"/var/app/current/node_modules/talib/build/Release/talib.node: cannot open shared object file: No such file or directory\",\"stack\":\"Error: /var/app/current/node_modules/talib/build/Release/talib.node: cannot open shared object file: No such file or directory\\n    at Object.Module._extensions..node.....
```

Anyone else experiencing this?

**Comment by oransel** [comment]
Are you running on Ubuntu or Amazon Linux?

Does this relate to your issue?
https://stackoverflow.com/questions/69879112/aws-lambda-how-to-fix-lib64-libm-so-6-version-glibc-2-29-not-found

**Comment by Milan4e** [comment]
Thanks for your reply. 

Yes I saw this post yesterday but was not able to install the package manually. What worked just 15min ago on the t3 instance, is updating the nodejs version to 18 and choosing the latest Amazon Linux image in AWS.

the t4g still does not work (although I would like to use t4g, since its faster and cheaper) and is throwing the same error as in my original post.

We can consider this resolved. Thanks again!

**Comment by oransel** [comment]
Sounds good. :)
