### ISSUE TITLE
ADD/DIV indicators doesn't works proper

### ISSUE THREAD

**Issue by gabrieldodan** [oransel/node-talib#14]
Hi

I have noticed some indicators form Math Operators group doesn't work proper, for example ADD or DIV. If you run a simple test like bellow you will get only NaN
```
talib.execute({
    name: 'ADD',
    inReal0: [1,1,1,1],
    inReal1: [2,2,2,2],
    startIdx:0,
    endIdx: 3
}, function(result) {
    console.log(result); //[NaN, NaN, NaN, NaN]
});

```

Any idea ? Thanks!

**Comment by oransel** [comment]
fixed with v0.4.1

https://github.com/oransel/node-talib/commit/20a6a7b95733a6938c479c54541ffc69eae3bb60
