### ISSUE TITLE
No error thrown on talib.execute if options object is invalid

### ISSUE THREAD

**Issue by vedraan** [oransel/node-talib#17]
Steps to reproduce:
Try setting the startIdx to a negative value (e.g. -100) and running talib.execute. It's strange that there is no error thrown and the callback doesn't get fired at all. Maybe an error callback might be good if success callback isn't called (it's not documented, maybe there is one?).

An easy solution is to of course do a validity check on data before even calling the talib.execute function, which is what I'm now doing. But it took a while to figure out what was wrong with the code.

My startIdx used:
`startIdx: marketData.close.length - limit - 1`
where limit was a preset limit to crop the marketData. The problem happened in one case where there wasn't enough market data to meet the limit so startIdx went to negative number.

Easy fix (used now):
`startIdx: Math.max(0, marketData.close.length - limit - 1),`

**Comment by oransel** [comment]
Will include parameter validation in the next release

**Comment by oransel** [comment]
please test 8329de99b41bed3d2ed6994624e0eb8697051fcb

**Comment by oransel** [comment]
fix is released https://github.com/oransel/node-talib/releases/tag/v0.5.0
