### ISSUE TITLE
calculate indicators by minutes

### ISSUE THREAD

**Issue by YoleYu** [oransel/node-talib#20]
Suppose now is 18:11, I have ten market data for  18:01, 18:02 ... 18:10.
I can use talib to calculate RSI of these data.

Now time goes to 18:12, I got the new data of  18:11.  
Can I use the calculated data previously as the input to calculate RSI for 18:12, or I can only use data of 18:01 - 18:11 as the input?

**Comment by oransel** [comment]
Please refer to this site for how RSI indicator works. 

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi
