### ISSUE TITLE
Unstable period and lookback

### ISSUE THREAD

**Issue by gabrieldodan** [oransel/node-talib#22]
Hi,

Is there any possibility to set the unstable period for indicators with memories? The unstable period is described here http://ta-lib.org/d_api/ta_setunstableperiod.html

**Comment by gabrieldodan** [comment]
Also, would be very useful(maybe on a next release) to export also the lookback functions: TA_SMA_Lookback() , TA_EMA_Lookback() etc

**Comment by oransel** [comment]
Unstable period is added 8797d5bcdea35c396d4944ea45f67f43f05b21e5

**Comment by oransel** [comment]
Lookback functions are a little tricky. I can't seem to find a way to call them in a generic fashion. Any suggestions?

**Comment by gabrieldodan** [comment]
Take a look at TA_GetLookback() function at ta_abstract/ta_abstract.c file, seems it is what you need.

**Comment by gabrieldodan** [comment]
Also, I think will be useful if you can implement Synch version of the lookback functions

**Comment by oransel** [comment]
I agree about the synchronous version of the lookback functions. The TA_GetLookback function retrieves the already set value of the lookback and it is not hard to implement, but there is no generic way of calling the lookback functions. They vary in parameters and they do not accept TA_ParamHolder type variable. We'll have to treat each lookback function as an individual function, which will take a lot of work to integrate. Unless, there is a generic way of calling them and I have not figured out yet.

**Comment by gabrieldodan** [comment]
Hi Mus,

Sorry for delay. I have tested  a bit the unstable period, seems to be working well.  The only thing I can't do is to set unstable period for all indicators. I see no code/id for TA_FUNC_UNST_ALL. Also, seems setting TA_FUNC_UNST_NONE has no effect. Any idea?

Regarding lookback functions. I understand will take a lot of work to implement. But I have noticed  that there are many functions that accept same numbers and same type of arguments. For example there are many functions that accept only optInTimePeriod argument. So we can group all functions by number-type of arguments. I think will be just a few groups. Look at candle functions, those that begin with "CDL", those functions accept 0 or 1 arguments, so we will have two groups here. We can assign a default lookback function for each group, for example for candle functions with 0 arguments we can assign TA_CDLDOJI_Lookback().  I can help you on grouping functions by number-type of arguments. What you think?

Thanks!

**Comment by oransel** [comment]
Hi Gabriel, looking into this. Sorry about the delay. I'll let you know once there is progress.

**Comment by gabrieldodan** [comment]
Hi Mus, no problem regarding delay. Thanks !

**Comment by gabrieldodan** [comment]
Hi Mus, let me know if you have any progress on this issue. Thanks!

**Comment by oransel** [comment]
Hi Gabriel, no update yet.
