### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gabrieldodan** [oransel/node-talib#23]
Hi

Seems when the library is used intensively it generate memory leak. Test case:
```
setInterval(function () {
    talib.execute({
        name: "ADX",
        startIdx: 0,
        endIdx: marketData.close.length - 1,
        high: marketData.high,
        low: marketData.low,
        close: marketData.close,
        optInTimePeriod: 9
    }, function (result) {

    });
}, 40);

```

Tested on node v0.12.2 and talib 0.5.0  

Any idea ? Thanks!

**Comment by oransel** [comment]
identified the issue. V8_TO_DOUBLE_ARRAY allocated memory is not given back.

**Comment by oransel** [comment]
Checked in a very primitive fix. 8797d5bcdea35c396d4944ea45f67f43f05b21e5

Please help testing.

**Comment by gabrieldodan** [comment]
Thanks Mus, I am testing now

**Comment by gabrieldodan** [comment]
FIXED !! Thanks a lot, really appreciate !

**Comment by oransel** [comment]
Sounds good. Thanks.
