### ISSUE TITLE
Unable to install on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by leokofi** [oransel/node-talib#25]
Hi All

I am not able to install node-talib on ubuntu the error that is returned is below;
hopefully someone can point me in the correct direction to resolve this issue.

Thanks in advance.
-------------------------------------------------------------------------------------------------------------------------------
building talib functions...
make: Entering directory `/opt/chobits040/node_modules/talib/build'
  CXX(target) Release/obj.target/talib/src/talib.o
make: g++: Command not found
make: *** [Release/obj.target/talib/src/talib.o] Error 127
make: Leaving directory `/opt/chobits040/node_modules/talib/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_                                                                                                                                                             modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074                                                                                                                                                             :12)
gyp ERR! System Linux 3.16.0-46-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/b                                                                                                                                                             in/node-gyp.js" "build"
gyp ERR! cwd /opt/chobits040/node_modules/talib
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Linux 3.16.0-46-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "talib"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE

npm ERR! talib@0.6.0 install: `node ./src/lib/build.js && node-gyp configure &&                                                                                                                                                              node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@0.6.0 install script 'node ./src/lib/build.js && no                                                                                                                                                             de-gyp configure && node-gyp build'.
npm ERR! This is most likely a problem with the talib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/lib/build.js && node-gyp configure && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls talib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/chobits040/npm-debug.log

**Comment by oransel** [comment]
You are missing GCC. Please install the build tools.

```Release/obj.target/talib/src/talib.o make: g++: Command not found make: *** ```

**Comment by leokofi** [comment]
thanks for the quick response... I have GCC installed

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by oransel** [comment]
can you make sure all the build essentials are installed by

```sudo apt-get install build-essential```

**Comment by leokofi** [comment]
Thanks sooo much Sir Oransel.. that worked....
