### ISSUE TITLE
MACD does not work as expected

### ISSUE THREAD

**Issue by stefanopiovesn** [oransel/node-talib#26]
I used AAPL data to calculate MACD(8, 17, 9) but the talib values are completely different from Google and Yahoo finance. SMA and EMA give the same values.
The issue is discussed here:
http://stackoverflow.com/questions/32169322/nodejs-talib-macd/32174156?noredirect=1#comment52275249_32174156

**Comment by Telemakhos** [comment]
Hi stefano, I think you have your answer here...

https://www.quantopian.com/posts/ta-dot-macd-values-dont-match-google-or-yahoo-finance-charts
