### ISSUE TITLE
npm install node-talib fail (OSX)

### ISSUE THREAD

**Issue by hungchai** [oransel/node-talib#27]
I am using node v4.1.1 and node-gyp v3.0.1, but it failed. Please advise me. Thanks
                             
10 errors generated.
make: *** [Release/obj.target/talib/src/talib.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Volumes/TOSHIBA EXT/Google Drive/nodejs_proj/node-stock-spider-v2/node_modules/talib
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install" "talib"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! talib@0.6.0 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the talib@0.6.0 install script 'node ./src/lib/build.js && node-gyp configure && node-gyp build'.
npm ERR! This is most likely a problem with the talib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/lib/build.js && node-gyp configure && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls talib
npm ERR! There is likely additional logging output above.

**Comment by oransel** [comment]
New version with node 4.x compatibility will be released this week.

**Comment by oransel** [comment]
published fix

**Comment by hungchai** [comment]
Thanks for your prompt action
