### ISSUE TITLE
Error installing on Ubuntu

### ISSUE THREAD

**Issue by cercao** [oransel/node-talib#29]
Hi! 
A tried to install and build on Ubuntu. I got the same error. 
I followed the recommendation described here too: https://github.com/oransel/node-talib/issues/10
This is the error on $npm install talib:
npm WARN package.json talib@1.0.0 No license field.

> talib@1.0.0 install /home/lucas/Documents/node-talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
make: Entering directory `/home/lucas/Documents/node-talib/build'
  CXX(target) Release/obj.target/talib/src/talib.o
../src/talib.cpp:42:11: error: ‘v8::MaybeLocal’ has not been declared
 using v8::MaybeLocal;
           ^
../src/talib.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Explain(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/talib.cpp:367:62: error: no matching function for call to ‘Nan::ReturnValue<v8::Value>::Set(v8::Handle<v8::Value>)’
     info.GetReturnValue().Set(TA_EXPLAIN_FUNCTION(*func_name));
                                                              ^
../src/talib.cpp:367:62: note: candidates are:
In file included from ../node_modules/nan/nan_callbacks.h:83:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/talib.cpp:29:
../node_modules/nan/nan_callbacks_12_inl.h:27:37: note: template<class S> void Nan::ReturnValue<T>::Set(const v8::Local<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const v8::Local<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_12_inl.h:27:37: note:   template argument deduction/substitution failed:
../src/talib.cpp:367:62: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const v8::Local<T>’
     info.GetReturnValue().Set(TA_EXPLAIN_FUNCTION(*func_name));
                                                              ^
In file included from ../node_modules/nan/nan_callbacks.h:83:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/talib.cpp:29:
../node_modules/nan/nan_callbacks_12_inl.h:32:37: note: template<class S> void Nan::ReturnValue<T>::Set(const Nan::Global<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const Global<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_12_inl.h:32:37: note:   template argument deduction/substitution failed:
../src/talib.cpp:367:62: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const Nan::Global<T>’
     info.GetReturnValue().Set(TA_EXPLAIN_FUNCTION(*func_name));
                                                              ^
In file included from ../node_modules/nan/nan_callbacks.h:83:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/talib.cpp:29:
../node_modules/nan/nan_callbacks_12_inl.h:46:15: note: void Nan::ReturnValue<T>::Set(bool) [with T = v8::Value]
   inline void Set(bool value) {
               ^
../node_modules/nan/nan_callbacks_12_inl.h:46:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘bool’
../node_modules/nan/nan_callbacks_12_inl.h:51:15: note: void Nan::ReturnValue<T>::Set(double) [with T = v8::Value]
   inline void Set(double i) {
               ^
../node_modules/nan/nan_callbacks_12_inl.h:51:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘double’
../node_modules/nan/nan_callbacks_12_inl.h:56:15: note: void Nan::ReturnValue<T>::Set(int32_t) [with T = v8::Value; int32_t = int]
   inline void Set(int32_t i) {
               ^
../node_modules/nan/nan_callbacks_12_inl.h:56:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘int32_t {aka int}’
../node_modules/nan/nan_callbacks_12_inl.h:61:15: note: void Nan::ReturnValue<T>::Set(uint32_t) [with T = v8::Value; uint32_t = unsigned int]
   inline void Set(uint32_t i) {
               ^
../node_modules/nan/nan_callbacks_12_inl.h:61:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘uint32_t {aka unsigned int}’
../node_modules/nan/nan_callbacks_12_inl.h:89:15: note: template<class S> void Nan::ReturnValue<T>::Set(S*) [with S = S; T = v8::Value]
   inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
               ^
../node_modules/nan/nan_callbacks_12_inl.h:89:15: note:   template argument deduction/substitution failed:
../src/talib.cpp:367:62: note:   mismatched types ‘S*’ and ‘v8::Handle<v8::Value>’
     info.GetReturnValue().Set(TA_EXPLAIN_FUNCTION(*func_name));
                                                              ^
../src/talib.cpp: In function ‘void Init(v8::Handle<v8::Object>, v8::Handle<v8::Object>)’:
../src/talib.cpp:1065:78: error: call of overloaded ‘SetAccessor(v8::Handle<v8::Object>&, v8::Local<v8::String>, Nan::NAN_GETTER_RETURN_TYPE (&)(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE))’ is ambiguous
     SetAccessor(exports, New<String>("functions").ToLocalChecked(), Functions);
                                                                              ^
../src/talib.cpp:1065:78: note: candidates are:
In file included from ../src/talib.cpp:29:0:
../node_modules/nan/nan.h:1922:13: note: bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)
 inline bool SetAccessor(
             ^
../node_modules/nan/nan.h:1878:13: note: void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)
 inline void SetAccessor(
             ^
../src/talib.cpp:1066:90: error: call of overloaded ‘SetAccessor(v8::Handle<v8::Object>&, v8::Local<v8::String>, Nan::NAN_GETTER_RETURN_TYPE (&)(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE))’ is ambiguous
     SetAccessor(exports, New<String>("functionUnstIds").ToLocalChecked(), FunctionUnstIds);
                                                                                          ^
../src/talib.cpp:1066:90: note: candidates are:
In file included from ../src/talib.cpp:29:0:
../node_modules/nan/nan.h:1922:13: note: bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)
 inline bool SetAccessor(
             ^
../node_modules/nan/nan.h:1878:13: note: void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)
 inline void SetAccessor(
             ^
make: *** [Release/obj.target/talib/src/talib.o] Error 1
make: Leaving directory `/home/lucas/Documents/node-talib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/lucas/Documents/node-talib
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! talib@1.0.0 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the talib@1.0.0 install script 'node ./src/lib/build.js && node-gyp configure && node-gyp build'.
npm ERR! This is most likely a problem with the talib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/lib/build.js && node-gyp configure && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls talib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lucas/Documents/node-talib/npm-debug.log
 

Could you help me ?

Thanks
Lucas

**Comment by oransel** [comment]
please upgrade to latest node

**Comment by cercao** [comment]
Ok! I gonna try!

**Comment by cercao** [comment]
Hi! Almost work!

Now I getting this message when I use 'npm install':
npm WARN package.json talib@1.0.0 No license field.
npm WARN cannot run in wd talib@1.0.0 node ./src/lib/build.js && node-gyp configure && node-gyp build (wd=/home/lucas/Documents/testeTalib/node-talib)

Could you help me ?

Thanks

**Comment by cercao** [comment]
Worked here!
I needed to set the reference to the right version:
sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node 

Thanks!
