### ISSUE TITLE
the callback don't follow node.js API standard signature (error parameter)

### ISSUE THREAD

**Issue by sulliwane** [oransel/node-talib#37]
Hello,

Here is current node-talib execute function signature:

``` javascript
talib.execute({ params }, (result) => console.log(result));
```

Is it intentional to not follow node.js standard callback signature? It should be like this:

``` javascript
talib.execute({ params }, (error, result) => console.log(result));
```

Seems the error will be thrown in the `result` value.

Thank you for your feedback!

**Comment by neopunisher** [comment]
ditto on this, it makes it hard to use with libs like async
