### ISSUE TITLE
node: symbol lookup error when trying to exec IMI 

### ISSUE THREAD

**Issue by neopunisher** [oransel/node-talib#39]
node: symbol lookup error: .../talib/build/Release/talib.node: undefined symbol: TA_IMI
what else do you need so this can be helpful? I see there are tests but haven't run them myself locally yet

**Comment by voidzero** [comment]
I'm getting this too. Were you able to solve it?

**Comment by voidzero** [comment]
@neopunisher any idea? @oransel maybe?

**Comment by oransel** [comment]
Is this resolved?

**Comment by laserlance** [comment]
I'm getting this on the two different Linux systems I tried it on. The TA_AVGDEV also returns "undefined symbol". I was running all of the functions to see if they worked when I found these issues. 

From what I can tell, these two functions are missing from this file: https://github.com/oransel/node-talib/blob/master/src/lib/make/csr/linux/g%2B%2B/ta_func/Makefile

They appear to be present in this file, however: https://github.com/oransel/node-talib/blob/master/src/lib/src/ta_func/Makefile.am

I also looked in the Windows version of the first linked file and those two functions are also absent there.

**Comment by laserlance** [comment]
@oransel I confirm that the entries for both the TA_IMI and TA_AVGDEV functions are missing from two Makefiles. The two files in question are:

1. https://github.com/oransel/node-talib/blob/master/src/lib/make/csr/linux/g%2B%2B/ta_func/Makefile

2. https://github.com/oransel/node-talib/blob/master/src/lib/make/csr/linux/g%2B%2B/ta_libc/Makefile

To get the install to work I had to manually download the package (look inside payload.json), extract and modify the files, then move the folder over to the computer where npm is and perform 
`npm pack ./talib-1.0.5/package`

Then, I installed the subsequent file using:
`npm install --unsafe-perm ./talib-1.0.0.5.tgz`

When editing the two files note that there are three different places in each file that need to be edited. Essentially, just copy/paste an existing entry and change the name of pasted entry for the three places. I am now able to use both the TA_IMI and TA_AVGDEV functions of the TALIB package.

**Comment by oransel** [comment]
@laserlance thank you for debugging this. I will submit a fix.

**Comment by oransel** [comment]
1b4f0ccab843288497124d1e3d9804d23abf5d5c added missing c file to makefile

**Comment by barrard** [comment]
Hey I know this is an old issue, but I'm getting this issue still 
 ```node: symbol lookup error: Release/talib.node: undefined symbol: TA_AVGDEV```
