### ISSUE TITLE
symbol lookup error: /app/build/Release/talib.node: undefined symbol: TA_Initialize

### ISSUE THREAD

**Issue by bharat383** [oransel/node-talib#41]
when i tried to deploy the code on Heroku and found the below error message : 
node: symbol lookup error: /app/build/Release/talib.node: undefined symbol: TA_Initialize
It's working fine on my local system with Mac OS.

**Comment by oransel** [comment]
I don't think this is an issue with the library. I didn't have Heroku in mind when making the library.
