### ISSUE TITLE
run example cdlhammer.js produces undefined

### ISSUE THREAD

**Issue by robomotic** [oransel/node-talib#42]
Hello there,
I have just installed the TA lib from npm with:
TALib Version: 1.0.2
I then run the cdlhammer.js on the input example json and I get undefined.
However if I do:
console.log(err)
I can see a time series which looks like the result e.g. a list with 0s and some 100s .
I am wondering if somehow the call back has swapped results with error?

**Comment by robomotic** [comment]
So basically this works:

```
// execute CDLHAMMER indicator function
talib.execute({
    name: "CDLHAMMER",
    startIdx: 0,
    endIdx: marketData.close.length - 1,
    open: marketData.open,
    high: marketData.high,
    low: marketData.low,
    close: marketData.close
}, function (err, result) {
	// Show the result array
    console.log("CDLHAMMER Function Results:");
    //console.log(err)
    console.log(err.result.outInteger.splice(0,50));

});
```

**Comment by kievking** [comment]
it's all undefined

**Comment by oransel** [comment]
good catch. latest version was not published to npm. try v1.0.3.

**Comment by kievking** [comment]
It's fine lol. It turns out that the err in callback is actually the result

**Comment by oransel** [comment]
yep, the repo was updated but the latest version was not pushed to npm to reflect the change. it was an update for another request.

**Comment by kievking** [comment]
It's good work
