### ISSUE TITLE
Indicator Result issues

### ISSUE THREAD

**Issue by bfree01** [oransel/node-talib#45]
Hi Mustafa,

first, thank you very much for contributing the code for free! 

After implementing node-talib to my code and comparing the results to freestockcharts, I've investigated that MinusDI and PlusDI seems to be mixed up. RSI as well - adding "100 - RSI" gives a result similar to what i can see at the other app. ADX, Stoch, MACD, they are all fine.
I'm not sure if I'm doing something wrong, as far what i've understood, the value [0] in the array is the one that needs to be updated on a new tick and the hole array needs to be unshifted.

Thank you for your feedback!

**Comment by oransel** [comment]
Hello. Thank you for using the module. I wish I could dedicate more time to improve the library. First task I would work on is to merge in the changes from others to support the windows platform.

Unfortunately, the module is pretty much a passthrough for talib. I am not sure if other platforms are doing post processing, but for this module, I opted for not manipulating the results.
