### ISSUE TITLE
Indicators documentation 

### ISSUE THREAD

**Issue by masalinas** [oransel/node-talib#51]
Anybody knows the best site where explain all the indicators??

**Comment by bfischer1121** [comment]
Yea really frustrating for a mature project to have zero documentation. No fault to node-talib - thanks for the work - but TA-LIBs website is poor.

**Comment by c10h22** [comment]
@masalinas maybe you can start here: http://ta-lib.org/function.html

**Comment by masalinas** [comment]
@c10h22 This was the first point where I started :). But any definition about the function ..
