### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by lionel95200x** [oransel/node-talib#53]
Hello
When windows support will be released ?
I got this error 
npm ERR! notsup Unsupported platform for talib@1.0.3: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x

Thanks for you help

**Comment by Carlitocool** [comment]
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /mnt/d/Asus/Desktop/gekko/node_modules/talib
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.0.3 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Carlitocool** [comment]
please help out

**Comment by oransel** [comment]
please use latest version
