### ISSUE TITLE
crossover function not found

### ISSUE THREAD

**Issue by travisstaloch** [oransel/node-talib#61]
windows 10, node v8.9.4, npm  v5.6.0

I'm trying to use the [crossover](https://tulipindicators.org/crossover) function from zenbot but it isn't found.  I've been able to use many of the the other talib functions with no problems after figuring out how to build talib with 2017 c++ msbuild tools and `npm install windows-build-tools`.  

```js
      talib.execute(
        {
          name: 'CROSSOVER',
          startIdx: 0,
          endIdx: series1.length - 1,
          inReal0: series1,
          inReal1: series2
        },
```
> {"error":"TA_FUNC_NOT_FOUND"}

Any idea how I can use this one or what is going on?

**Comment by laserlance** [comment]
There is no such function in the underlying TA-LIB library. [See the Functions Here](https://www.ta-lib.org/function.html)
Essentially, if it's not listed there, then it's not going to be available via this wrapper.
