### ISSUE TITLE
Update Readme for Windows

### ISSUE THREAD

**Issue by xiva-wgt** [oransel/node-talib#63]
Please added/update install notes for windows users.

Prerequisites for windows

You will need to install the following build tools for .NET 4.6. If you have already done this before on your computer (or you have Visual Studio 2015 installed), please skip to step 2.

1. If you're running an Windows version older than Windows 10, download and run the .NET Framework 4.6.2 [link](https://go.microsoft.com/fwlink/?LinkId=780596) installer. On Windows 10 and higher, the .NET Framework 4.6 is already included.
2. Install [Windows Build Tools](https://www.npmjs.com/package/windows-build-tools).
3. Download and run the [.NET Framework 4.6 Targeting Pack](https://www.microsoft.com/ru-ru/download/details.aspx?id=48136) installer. When the download page prompts you which file to download, select NDP46-TargetingPack-KB3045566.exe.

**Comment by xiva-wgt** [comment]
.NET Framework 4.6 Targeting Pack not included Windows Build Tools npm package.

**Comment by ynzheng** [comment]
Done all above(installed .NET Framework 4.6.2, .NET Framework 4.6 Targeting Pack,Windows Build Tools.) on Windows 7 

but

![image](https://user-images.githubusercontent.com/107111/46572091-ce75fa00-c9b2-11e8-9790-ca93bd29e532.png)


$ yarn global add windows-build-tools
yarn global v1.10.1
warning package.json: No license field
[1/4] Resolving packages...
warning windows-build-tools > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "windows-build-tools@5.0.0" has no binaries
Done in 31.45s.

$ npm install --global --production windows-build-tools

> windows-build-tools@5.0.0 postinstall E:\Server\ScoopGlobalApps\apps\nvm\current\nodejs\nodejs\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\zyn\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\zyn\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Action start 21:55:49: MsiPublishAssemblies.
Action ended 21:55:49: MsiPublishAssemblies. Return value 1.
Action start 21:55:49: PublishFeatures.
Action ended 21:55:49: PublishFeatures. Return value 1.
Action start 21:55:49: PublishProduct.

Now configuring the Visual Studio Build Tools and Python...

All done!

+ windows-build-tools@5.0.0
updated 1 package in 34.15s

**Comment by xiva-wgt** [comment]
https://www.npmjs.com/package/windows-build-tools

**Comment by ynzheng** [comment]
> https://www.npmjs.com/package/windows-build-tools - [Windows Vista / 7 only] requires .NET Framework 4.5.1 (Currently not installed automatically by this package)

It seems I canot install 4.5.1 now,cos I have installed  .NET Framework 4.6.2 and  the .NET Framework 4.6 Targeting Pack ...

any help?

**Comment by xiva-wgt** [comment]
npm install -g npm ? update npm.

**Comment by xiva-wgt** [comment]
npm install -g node-gyp
and
npm config set node_gyp "node C:\Users\me\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js"
find you node-gyp.js path
