### ISSUE TITLE
talib MACD return null

### ISSUE THREAD

**Issue by HiepNinh** [oransel/node-talib#66]
I'm using talib v1.0.3. Nodejs v9. Here is my code:
```
talib.execute({
        name: "MACD",
        startIdx: 0,
        endIdx: end,
        inReal: Data,
        optInFastPeriod: 12,
        optInSlowPeriod: 26,
        optInSignalPeriod: 9
    }, function (result) {
        console.log(result);
    });
```
The result is null. Could anyone know the reason please help me solve this stuff. Thank in advance.

**Comment by fabiojsousa** [comment]
Is there some place that I can find some documentation about the parameters and how many data I need?

**Comment by fkotsian** [comment]
If anyone's out here hitting this in 2021, the ans is `the callback signature is (err, data)`: I didn't get it til I checked out the examples in https://github.com/oransel/node-talib/blob/master/examples/adx.js#L21

Great lib tho!
