### ISSUE TITLE
Error on ubuntu installa

### ISSUE THREAD

**Issue by ialberquilla** [oransel/node-talib#67]
Hi, 

I'm trying to install the talib in node with the instruction: 

`npm install talib`

 But after compiling sources it fails with the error:

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ivan/gekko/gekko/node_modules/talib/build'
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /home/ivan/gekko/gekko/node_modules/talib
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.0.5 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

I tried it with sudo user with the same result, and changing the permission of the directory, but nothing works, any idea?

Thanks

**Comment by oransel** [comment]
you may not have permission to the folder you are trying to install
