### ISSUE TITLE
Finding horizontal support / resistance possible?

### ISSUE THREAD

**Issue by Swiftnesses** [oransel/node-talib#78]
Good day,

Thank you for this superb lib, much appreciated!

I was wondering if it was possible to find horizontal support / resistance levels using the lib (either directly, or via store / analyse).

Many thanks in advance.

**Comment by oransel** [comment]
I am not sure if what you are looking for is directly in the library, but there are ways to use the outputs of the functions in the library to combine and determine the support and resistance levels.
