### ISSUE TITLE
the work object isn't deleted in Sync mode, it will cause memory leak

### ISSUE THREAD

**Issue by IanXia** [oransel/node-talib#83]
if (isSync) {
        wo->retCode = TA_CallFunc((const TA_ParamHolder *)wo->func_params, wo->startIdx, wo->endIdx, &wo->outBegIdx, &wo->outNBElement);
        info.GetReturnValue().Set(generateResult(wo));
        return;
    }

**Comment by Insider77** [comment]
Any solution?

**Comment by oransel** [comment]
Will investigate

**Comment by oransel** [comment]
Please check latest commit
