### ISSUE TITLE
talib osx Illegal instruction: 4

### ISSUE THREAD

**Issue by omega1119** [oransel/node-talib#84]
Hi there,

I'm using talib with node 13.0.1, npm 6.12.0 on osx 10.14.6. It normally works fine as well as on my raspberry pi 4, however today when I started my node application I received this error message:

#
# Fatal error in , line 0
# Check failed: receiver.IsJSFunction().
#
#
#
#FailureMessage Object: 0x7ffeefbf40a0sh: line 1:  4907 Illegal instruction: 4  node ./dist/main.js

Removing talib references from my code fixes the issue. Has anyone else experienced this, or know how to fix it? I tried deleting and installing my node_module folder.

Thanks

**Comment by oransel** [comment]
I have not been able to test it with node 13 yet. I'll try to allocate time to test.

**Comment by omega1119** [comment]
Hi, sorry I forgot to mention it's also happening on npm 6.12.0 and node 10.15.3. I upgraded to node 13 thinking it might help fix the issue.

**Comment by omega1119** [comment]
It's the same for node 12.13.0. Not sure if that helps at all?

**Comment by oransel** [comment]
Are you installing from npm or git?

**Comment by omega1119** [comment]
I'm installing from npm.

**Comment by oransel** [comment]
Can't replicate it.

```
~/Desktop/test % node -v
v10.17.0
~/Desktop/test % ls
node_modules      package-lock.json test.js
~/Desktop/test % cat test.js
const talib = require("talib");

console.log(talib.version);
~/Desktop/test % node test.js
1.1.3
~/Desktop/test %
```

**Comment by omega1119** [comment]
Ok no problem, thanks for having a look!

**Comment by omega1119** [comment]
If I can solve the issue on my side I will post an update with what I think went wrong.

**Comment by omega1119** [comment]
Hi,

I think I know what it may be:

return talib.execute({
            name: "BBANDS",
            inReal: marketData.close,
            startIdx: 0,
            endIdx: marketData.close.length - 1,
            optInTimePeriod: optInTimePeriod,
            optInNbDevUp: 2,
            optInNbDevDn: 2,
            optInMAType: 0
        }) as IBBANDS;

when I pass in marketData.close as a 0 length array it throws that error. optInTimePeriod is = 9.

**Comment by oransel** [comment]
Good catch. I need to add parameter value checking to the execute function. I'll try to schedule some time to do this. In the meanwhile, you can prevent it from crashing by checking it in your application before passing it to talib.

**Comment by omega1119** [comment]
Thanks, no problem. I'm doing validation in my application for the time being. Close the issue when you're ready.

**Comment by karangarg45** [comment]
@omega1119 i am facing the same issue? Do you have any pointers to fix the issue? I have also tried adding an empty array check.

**Comment by omega1119** [comment]
@karangarg45 sorry for the late reply, the issue I had was in the .execute(), I was passing in a 0 length array into the inReal parameter. You would need to do some validatrion to make sure the array has values. I used an if statement like this:

`if (marketData.close.length > 0) {
            retunValue = talib.execute({
                name: "BBANDS",
                inReal: marketData.close,
                startIdx: 0,
                endIdx: marketData.close.length - 1,
                optInTimePeriod: optInTimePeriod,
                optInNbDevUp: 2,
                optInNbDevDn: 2,
                optInMAType: 0
            });
        }`

**Comment by omega1119** [comment]
@karangarg45 do you have an example of what you are doing in code?
