### ISSUE TITLE
tablib illegal hardware instruction on osx

### ISSUE THREAD

**Issue by vanphandinh** [oransel/node-talib#88]
![Screen Shot 2020-12-09 at 11 18 23 PM](https://user-images.githubusercontent.com/13887599/101656043-d63ef680-3a74-11eb-9bc6-ffffe8ee2425.png)
![Screen Shot 2020-12-09 at 11 18 36 PM](https://user-images.githubusercontent.com/13887599/101656062-ddfe9b00-3a74-11eb-8f9b-06962d051e93.png)

I've tried to detect the candle patterns but I faced this problem. 
How to fix it?
I ran on node 10.

**Comment by oransel** [comment]
Can you provide complete example with data? and which OS are you using?

**Comment by admapop** [comment]
I just encountered the same issue. Are you trying to run it synchronously? Try the callback version, that got rid of the error for me.

**Comment by vanphandinh** [comment]
Yes, I think the async call is not working but the sync call works perfectly. 
In addition, the default value is not working, I have to pass the value manually.

**Comment by oransel** [comment]
Can you post a complete example demonstrating the issue? 

I tested with node v14.15.1 and following 2 examples worked fine.

```
talib.execute({
    name: "ADX",
    startIdx: 0,
    endIdx: marketData.close.length - 1,
    high: marketData.high,
    low: marketData.low,
    close: marketData.close,
    optInTimePeriod: 9
}, function (err, result) {
    console.log("ADX Function Results:");
    console.log(result);
});
```

```
const result = talib.execute({
    name: "ADX",
    startIdx: 0,
    endIdx: marketData.close.length - 1,
    high: marketData.high,
    low: marketData.low,
    close: marketData.close,
    optInTimePeriod: 9
});
console.log("ADX Function Results:");
console.log(result);
```

**Comment by vanphandinh** [comment]
Can you retest with some candlestick pattern functions?

**Comment by admapop** [comment]
Just to update, for me it seems to have either been something to do with the Node version, or a missing prop in execute.

Both async and sync work now. This is for indicators, not candlestick pattern functions.
