### ISSUE TITLE
It's a bit confusing that talib.explain shows defaultValue but options are mandatory or else it crashes

### ISSUE THREAD

**Issue by BaptisteGarcin** [oransel/node-talib#90]

**Comment by oransel** [comment]
It seems like we need an upgrade to this module. 

https://github.com/oransel/node-talib/issues/89#issuecomment-782927949 can be handled as well at the same time.

**Comment by BaptisteGarcin** [comment]
lmk if I can help

**Comment by oransel** [comment]
@BaptisteGarcin can you please provide an example?
