### ISSUE TITLE
Cannot import talib.node

### ISSUE THREAD

**Issue by digimbyte** [oransel/node-talib#91]
built it on windows, Talib/build/Release/talib exists
but cannot import.
`import * as talib from 'talib/build/Release/talib';`
```
Cannot find module 'D:\development\trade-trends\node_modules\talib\build\Release\talib' 
imported from D:\development\trade-trends\app.mjs
Did you mean to import talib/build/Release/talib.node?
```
![image](https://user-images.githubusercontent.com/6645396/109607918-b8b19280-7b74-11eb-8e68-9b7075f6f8b9.png)

I do not build my app as there is nothing to compile - suggestions?
using Node v15.10.0

**Comment by danyinfo1** [comment]
same issue, any update?

**Comment by reynard80** [comment]
Same here.

**Comment by oransel** [comment]
Newer style imports are not supported.
