### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by guidors** [oransel/node-talib#92]
Hi,

Great lib! 
And I wanted to use it on FreeBSD. A port devel/ta-lib already exists for FreeBSD and it was an easy change to have node-talib use this port. 
I created a commit on my fork: https://github.com/guidors/node-talib/commit/6fa02492f75fc79fdac8d2b9aa2880056c126ebe.
If you like it may be this can be incorporated in your repo.

Best regards,

Guido

**Comment by oransel** [comment]
Thank you for update. If tested, please submit a pull request and we can upgrade the module with your changes.
