### ISSUE TITLE
STOCHRSI LOOKBACK_CALL change

### ISSUE THREAD

**Issue by ericauv** [oransel/node-talib#96]
How can I change the lookback function used for in the STOCHRSI function (see https://www.gitmemory.com/issue/mrjbq7/ta-lib/203/482133912)?

I've tried making this change in `node_modules/talib/src/lib/src/ta_func/ta_STOCHRSI.c` and then running `npm run install` in `node_modules/talib`, but the STOCHRSI values are still off.

**Comment by oransel** [comment]
Out of scope of this node.js wrapper
